## Día 1
Referencia : [TEQS](https://github.com/The-Eigensolvers/TEQS)

In [1]:
import numpy as np 

#### Números complejos

In [28]:
print('Hola Peter\n')

# Números complejos
z = 3+4j

mag = np.abs(z)
arg = np.angle(z)
print("magnitud: ",mag,"\nangulo: ",arg)

Re = np.real(z)
Im = np.imag(z)
print("Parte real: ",mag,"\nParte imaginaria: ",Im)

Hola Peter

magnitud:  5.0 
angulo:  0.9272952180016122
Parte real:  5.0 
Parte imaginaria:  4.0


In [2]:
# Operaciones entre complejos
z1 = 1 + 2j
z2 = 3 + 4j

print("suma:",z1+z2)
print("Multiplicación:",z1*z2)
print("División:",z1/z2)


suma: (4+6j)
Multiplicación: (-5+10j)
División: (0.44+0.08j)
PREGUNTA


In [30]:
# Conjugación 
z1 = 3 + 4j
z2 = np.conj(z1)

print("z1:",z1)
print("z1*:",z2)
print("|z1|^2:",z1*z2)

z1: (3+4j)
z1*: (3-4j)
|z1|^2: (25+0j)


#### Espacios vectoriales

In [34]:
# Cómo escribimos un vector en python? -> No usando listas
evil_vector1 = [1,2,3]
evil_vector2 = [1,2,3]
escalar = 3

print(evil_vector1)
print(evil_vector2)
print("evil_suma: ",evil_vector1+evil_vector2)
print("evil_prod: ",escalar*evil_vector2)

[1, 2, 3]
[1, 2, 3]
evil_suma:  [1, 2, 3, 1, 2, 3]
evil_prod:  [1, 2, 3, 1, 2, 3, 1, 2, 3]


In [35]:
# Los representamos mediante arreglos de numpy
vector1 = np.array([1,2,3])
vector2 = np.array([1,2,3])
escalar = 3

print(vector1)
print(vector2)
print("suma: ",vector1+vector2)
print("prod: ",escalar*vector2)

[1 2 3]
[1 2 3]
suma:  [2 4 6]
prod:  [3 6 9]


#### Normalización

In [47]:
# Normalizando vectores
v = np.array([-1,2,3])
print("vector:", np.abs(v))

norma = np.sqrt((-1)**2 + 2**2 + 3**2)
print("norma: ",norma)

vector: [1 2 3]
norma:  3.7416573867739413


In [50]:
v_unitario = v/norma
print("vector unitario:",v_unitario)

vector unitario: [-0.26726124  0.53452248  0.80178373]
componente 1: -1


In [52]:
# Acceder a los elementos de un arreglo
print("componente 1:",v[0])
print("componente 1:",v[1])
print("componente 1:",v[2])

componente 1: -1
componente 1: 2
componente 1: 3


In [58]:
# Normalicemos nuevamente accediendo a las componentes
v = [-1,2,3]
v_abs = np.abs(v)
v_abs_cuadrado = v_abs**2
norma_cuadrado = np.sum(v_abs_cuadrado)
norma = np.sqrt(norma_cuadrado)
v_unitario = v/norma

print("vector:",v)
print("abs_vector:",v_abs)
print("abs_vector^2:",v_abs_cuadrado)
print("norma^2:",norma_cuadrado)
print("norma:",norma)
print("vector unitario:",v_unitario)

vector: [-1, 2, 3]
abs_vector: [1 2 3]
abs_vector^2: [1 4 9]
norma^2: 14
norma: 3.7416573867739413
vector unitario: [-0.26726124  0.53452248  0.80178373]


In [60]:
# De forma simplificada
v = [-1,2,3]
v_unitario = v / np.sqrt(np.sum( np.abs(v)**2 ))

print(v_unitario)

[-0.26726124  0.53452248  0.80178373]


### Producto interno

In [61]:
# Producto interno np.inner
# R^3
u = np.array([1,2,3])
v = np.array([4,5,6])

np.inner(u,v)

32

In [76]:
# Now in C^2
u = np.array([1+2j,3+4j])
v = np.array([2+1j,4+3j])

np.inner(np.conj(u),v)

(28-10j)

#### Dirac's notation

In [96]:
# Construyendo un módulo

def ket(vec):
    ket = np.array(vec)
    return ket.reshape(-1,1)

def bra(vec):
    bra = np.array(vec)
    return bra.conj().reshape(1,-1)

def braket(bra,ket):
    return np.inner(bra.flatten(),ket.flatten())

def ketbra(bra,ket):
    return ket*bra

def normalize(ket):
    norm = braket(bra(ket),ket)
    return 1/np.sqrt(norm) * ket

def isOrthogonal(ket1,ket2):
    bra1 = bra(ket1)
    inner = braket(bra1,ket2)
    return bool(inner == 0)

In [106]:
# Probando las funciones

u = [1+1j, 0, 1,-3]
v = [2j, 0, 0, 3+1j]

k = ket(u)
b = bra(v)

prod_int = braket(b,k)
prod_ext = ketbra(b,k)

u_norm = normalize(k)

orth = isOrthogonal(k,b)

print('|u> =\n',k)
print('\n<v| =', b)
print('\n<v|u> =', prod_int)
print('\n|u><v| =\n', prod_ext)
print('\n|u> normalizado =\n ', u_norm)
print('\n|u> y |v> son ortogonales?:', orth)

|u> =
 [[ 1.+1.j]
 [ 0.+0.j]
 [ 1.+0.j]
 [-3.+0.j]]

<v| = [[0.-2.j 0.-0.j 0.-0.j 3.-1.j]]

<v|u> = (-7+1j)

|u><v| =
 [[ 2.-2.j  0.+0.j  0.+0.j  4.+2.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.-2.j  0.+0.j  0.+0.j  3.-1.j]
 [ 0.+6.j  0.+0.j  0.+0.j -9.+3.j]]

|u> normalizado =
  [[ 0.28867513+0.28867513j]
 [ 0.        +0.j        ]
 [ 0.28867513+0.j        ]
 [-0.8660254 +0.j        ]]

|u> y |v> son ortogonales?: False


#### Qubits

In [114]:
zero = ket([1,0])
print("|0> = \n",zero)
one = ket([0,1])
print("|1> = \n",one)

|0> = 
 [[1]
 [0]]
|1> = 
 [[0]
 [1]]
